### PR TITLE
Fix issue #474

### PR DESCRIPTION
**Pull request by kausmees**
Added preprocessor directives to use different functions dependent on the SFML version.

### CODE REVIEW

**Comment by kausmees** [comment]
Opps, I realized this code won't work for SFML major versions > 2 (then there should be no constraint on the minor version), so that should probably be fixed before accepting the pull request.

**Comment by richelbilderbeek** [comment]
@kausmees the tests pass and we have the mantra 'If all tests pass, we are -by definition- happy'. Sure, if team members discover their build fails, we'll fix it :-)

**Comment by TheoPannetier** [comment]
> Oops, I realized this code won't work for SFML major versions > 2 (then there should be no constraint on the minor version), so that should probably be fixed before accepting the pull request.

I pushed a change solving this with an elif 😉

**Review by TheoPannetier — APPROVED** [review]
Brilliant work, thanks!
The only downside I see is that every time we'll want to colour something we'll have to add these preprocessor statements, and they could take a lot of lines if we have many things to colour... One could make a custom colouring function so these are only evaluated once in the entire code, but I think it's not an issue rn.

**Pull request merged**
