### PR TITLE
Fixed issue #376

### PR DESCRIPTION
**Pull request by Tingvall**

### CODE REVIEW

**Review by TheoPannetier — CHANGES_REQUESTED** [review]
Nice start, but I think #376 is not solved yet - apologies if I'm mistaken! I believe one of the two functions could also be ditched, as suggested in #376.

**Comment by Tingvall** [comment]
Me and Richel got it to work on mac, that is the new stuff. Ignore in review.

**Comment by richelbilderbeek** [comment]
@Tingvall: I do agree that the `.pro` files can be ignored in the review, but the `#ifdef USE_MAC`s should be removed before merging to `develop` I think. Who wrote that in the first place :smirk:?

**Comment by kausmees** [comment]
We removed one of the functions, and renamed the other one get_value().
Also removed the preprocessor #ifdef USE_MAC directives from all files, and it worked when we tested on a mac!

**Review by TheoPannetier — APPROVED** [review]
Excellent! #376 is clearly addressed here, no further comments.
Huge thanks for getting it to work for Mac users 🍎

**Pull request merged**
